# Generated by Django 4.2.2 on 2023-06-11 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(default='', max_length=4, unique=True)),
                ('capacity', models.IntegerField(default=2)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(default='', max_length=8, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('group', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_attending', models.BooleanField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
