# Generated by Django 4.2.2 on 2023-06-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_table_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='wedding_id',
        ),
    ]
