# Generated by Django 4.2.2 on 2023-06-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_guest_guest_id_remove_table_table_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.table'),
        ),
    ]
