# Generated by Django 4.2.2 on 2023-06-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_guest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wedding'),
        ),
    ]
