# Generated by Django 4.2.2 on 2023-06-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_table_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='api.table'),
        ),
    ]
