# Generated by Django 4.2.2 on 2023-12-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
